// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB3FmrFW7M90-FwWXmWBy2J15jFy9JZsE',
    appId: '1:929597652191:web:46707d9e2b660de65bfd6a',
    messagingSenderId: '929597652191',
    projectId: 'uas-apkmobile-a122106621',
    authDomain: 'uas-apkmobile-a122106621.firebaseapp.com',
    storageBucket: 'uas-apkmobile-a122106621.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBihws1KZwzS-GewBc_JyfSmZS7j9NHk9c',
    appId: '1:929597652191:android:d9a32f8f75db54d55bfd6a',
    messagingSenderId: '929597652191',
    projectId: 'uas-apkmobile-a122106621',
    storageBucket: 'uas-apkmobile-a122106621.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB3FmrFW7M90-FwWXmWBy2J15jFy9JZsE',
    appId: '1:929597652191:web:4a86d571cab1abb15bfd6a',
    messagingSenderId: '929597652191',
    projectId: 'uas-apkmobile-a122106621',
    authDomain: 'uas-apkmobile-a122106621.firebaseapp.com',
    storageBucket: 'uas-apkmobile-a122106621.appspot.com',
  );
}
